

spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    validate-on-migrate: true